
classDiagram



    class Event {
        <<interface>>
    }

    class BusEvent {
        <<interface>>
    }
    class BusStationsLoaded {
        +List~Station~ stations
    }
    class BusDeparturesLoaded {
        +List~Departure~ departures
    }

    class AirplaneEvent {
        <<interface>>
    }
    class AirportsLoaded {
        +List~Station~ airports
    }
    class AirplaneDeparturesLoaded {
        +List~Departure~ departures
    }
    class AirplaneArrivalsLoaded {
        +List~Arrival~ arrivals
    }

    Event <|-- BusEvent
    Event <|-- AirplaneEvent
    BusEvent <|-- BusStationsLoaded
    BusEvent <|-- BusDeparturesLoaded
    AirplaneEvent <|-- AirportsLoaded
    AirplaneEvent <|-- AirplaneDeparturesLoaded
    AirplaneEvent <|-- AirplaneArrivalsLoaded

