name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SBT dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build and Test
        run: sbt clean compile test fastLinkJS

      - name: Create index.html
        run: |
          mkdir -p target/scala-3.4.1/classes
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta charset="UTF-8">
              <title>Tyrian App</title>
            </head>
            <body>
              <div id="app"></div>
              <script type="text/javascript" src="./main.js"></script>
            </body>
          </html>' > target/scala-3.4.1/classes/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/scala-3.4.1/classes