name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Build with Parcel
        run: yarn build

        # Build Docusaurus docs
      - name: Install dependencies for Docusaurus
        run: |
          cd docs
          npm install

      - name: Build Docusaurus
        run: |
          cd docs
          npm run build

      # Combine outputs
      - name: Prepare deployment
        run: |
          mkdir -p public
          cp -R dist/* public/
          cp -R docs/build/* public/docs/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public